language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email:
    recipients:
      - qwxy9638@gmail.com
    on_success: change
    on_failure: always
